# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# Spring配置
spring:
  application:
    name: order-management-system
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/order_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  # 安全配置
  security:
    user:
      name: admin
      password: admin123
  
  # 国际化配置
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600

# 日志配置
logging:
  level:
    com.example.order: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/order-management.log
    max-size: 10MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger配置
springfox:
  documentation:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

# JWT配置
jwt:
  secret: ${JWT_SECRET:orderManagementSecretKey2024}
  expiration: 86400000  # 24小时
  refresh-expiration: 604800000  # 7天

# 应用自定义配置
app:
  # 分页配置
  pagination:
    default-page-size: 20
    max-page-size: 100
  
  # 文件上传配置
  upload:
    max-file-size: 10MB
    allowed-file-types: jpg,jpeg,png,pdf,doc,docx
  
  # 缓存配置
  cache:
    ttl: 3600  # 1小时
  
  # 业务配置
  business:
    max-order-amount: 1000000  # 最大订单金额
    min-order-amount: 1        # 最小订单金额
    default-currency: CNY      # 默认货币 